/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...page404]': RouteRecordInfo<'/[...page404]', '/:page404(.*)', { page404: ParamValue<true> }, { page404: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/projets/Crac': RouteRecordInfo<'/projets/Crac', '/projets/Crac', Record<never, never>, Record<never, never>>,
    '/projets/DuaLipa': RouteRecordInfo<'/projets/DuaLipa', '/projets/DuaLipa', Record<never, never>, Record<never, never>>,
    '/projets/Stellaris': RouteRecordInfo<'/projets/Stellaris', '/projets/Stellaris', Record<never, never>, Record<never, never>>,
    '/projets/Yumin': RouteRecordInfo<'/projets/Yumin', '/projets/Yumin', Record<never, never>, Record<never, never>>,
  }
}
